version: "3.8"

services:
  auth-backend:
    build:
      context: .
    container_name: auth_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_DDL_AUTO=${SPRING_JPA_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
      - SPRING_JPA_DIALECT=${SPRING_JPA_DIALECT}
    volumes:
      - ./firebase.env:/app/firebase.env
      - ./.env:/app/.env
    networks:
      - devNetworkArq
    restart: unless-stopped

networks:
  devNetworkArq:
    external: true

