version: '3.8'

services:
  autenticacion-postgres:
    image: postgres:13
    container_name: autenticacion-postgres
    restart: always
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - autenticacion_pgdata:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    restart: unless-stopped
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      -  kafka_data:/bitnami/kafka/data
      -  kafka_data:/opt/bitnami/kafka/logs
    ports:
      - "9092:9092"

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=no
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=adminRetoChimba
      - ZOO_SERVER_PASSWORDS=adminPasswordRC
      - ZOO_CLIENT_USER=clientRetoChimba
      - ZOO_CLIENT_PASSWORD=clientPasswordRC
      - ZOO_PORT_NUMBER=2181
      - ZOO_TICK_TIME=2000
      - ZOO_INIT_LIMIT=5
      - ZOO_SYNC_LIMIT=2
      - ZOOKEEPER_SASL_ENABLED=false
    volumes:
      - zookeeper_data:/bitnami/zookeeper/data
      - zookeeper_data:/bitnami/zookeeper/logs
    ports:
      - "2181:2181"

volumes:
  kafka_data: 
  autenticacion_pgdata:
  zookeeper_data:
