name: Production Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and deploy microservice
      working-directory: ${{ github.workspace }}
      run: |
        cd $GITHUB_WORKSPACE
        mvn clean package -DskipTests
        docker-compose down
        docker-compose build --no-cache
        docker-compose up -d
